language: scala
scala:
- 2.11.7
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database "akka-http-rest-test";' -U postgres
script: sbt test
deploy:
  provider: heroku
  api_key:
    secure: {{HEROKU_SECRET_KEY}}
